{% set version = "4.13.2" %}

package:
  name: pcas
  version: {{ version }}

source:
  git_url: https://github.com/epics-modules/pcas.git
  git_tag: v{{ version }}

build:
  number: 14

requirements:
  build:
    - {{ compiler ('c') }}
    - {{ compiler ('cxx') }}
  host:
    - epics-base >=7
  run:
    - epics-base >=7
